### ISSUE TITLE
Display state of lockdown

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/lockdown#11]
Decided in call:

- Red: In lockdown
- Green: no lockdown
- None: No information present.

**Comment by JFQueralt** [comment]
After deeper thinking, 4 scenarios as a result of 2 non-correlated properties:
- Whether a country has cases
- Whether the country has decided to go on lockdown

That brings 4 possibilities that I resumed in the Front-End Tab on the Data Source.
