### ISSUE TITLE
[backend] minify json before saving

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#116]
We should minify the json files before saving them, this should only be needed once and only for:

- [ ] worldmap.json
- [ ] population.json

**Comment by ilyasfoo** [comment]
I'm going to argue to it's not necessary at this point, as `JSON.stringify` from our objects are already without any extra whitespaces. Let me know if you found it otherwise

**Comment by thepassle** [comment]
> I'm going to argue to it's not necessary at this point, as `JSON.stringify` from our objects are already without any extra whitespaces. Let me know if you found it otherwise

Yep, you're totally right, I got mixed up with the json files. Sorry, my bad. We should still do it for the worldmap and population, but it only needs to be done once for this files.

**Comment by ilyasfoo** [comment]
Agreed 👍
