### ISSUE TITLE
[frontend] Cache invalidation for services

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#141]
We should add some way to invalidate the in memory caches in the services. The service worker strategy for these requests is NetworkFirst because we want fresh data and cached data when offline, but in the service itself we _also_ cache it in memory. This means if a user has their tab open indefinitely, they will only get fresh data once (the first time).

Example:
A user clicks the 'updates' item in the menu bar. Fresh data is fetched. The user continues to use the app, and an hour later decides to check the updates again; a response is returned from the in memory cache of the service, so the user wont see an update.

Maybe we should add a timer on it? To fetch fresh data if the latest fetch was like, half an hour old or something?

**Comment by Calebyang93** [comment]
The service worker is in which file? I can work on updating the timer for that.
