### ISSUE TITLE
When we mouse over on a country, it would be good if we highlight that country and display the info right there. 

### ISSUE THREAD

**Issue by prahlad1989** [Code-for-All/lockdown#153]

**Comment by thepassle** [comment]
Im not sure about this, both for performance and accessibility reasons. If a user would move their mouse across a continent, many countries would have to be highlighted, which means that _many many_ requests will be fired (each country details dialog does 3 requests), basically destroying the users device's storage as well as eating up all their data (if not on wifi). 
Additionally showing essential information on hover is generally bad practice in terms of accessibility.

**Comment by prahlad1989** [comment]
You mean touch screen? I din't have touch screen in mind..

**Comment by thepassle** [comment]
Okay I'll close this
