### ISSUE TITLE
Fix: unify the colors with styleguide

### ISSUE THREAD

**Issue by davojta** [Code-for-All/lockdown#183]
Current colors:
--ld-blue-1: #6D9EEB;
--ld-blue-2: #C382F6;
--ld-yellow-1: #F6B26B;
--ld-green-1: #93C47D;
--ld-red-1: #E06666;

Map background #F2F2F2

No data #CCCCCC

**Comment by aherreDev** [comment]
This issue have to be open? I think that the problem is solved

**Comment by davojta** [comment]
the issue described is solved
