### ISSUE TITLE
Minify `csz` tagged template literals in the build

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#54]

**Comment by LarsDenBakker** [comment]
This may be possible with https://github.com/cfware/babel-plugin-template-html-minifier but we have to be careful with the sass-like syntax that's supported by csz.

**Comment by thepassle** [comment]
We could run the ```css`` ``` templates through `stylis` before passing them to template-html-minifier maybe

**Comment by thepassle** [comment]
Ah I dont think that'll work because I think `csz` does Stylis at runtime, so you'll get different classes?

**Comment by LarsDenBakker** [comment]
We could replace it with a version that doesn't do it runtime. In the end we don't have so many styles, so I don't think it's really something you're going to notice.
