### ISSUE TITLE
totals.json gets loaded twice because of race condition

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#58]
on page load, `totals.json` gets loaded twice

whats happening is that `<${Totals}>` which calls the `totalsService` is used in two components, in `<${MainPage>` and in `<${Header>`, my guess is that on initial pageload, both `totalsService.getTotals()` are ran, and they both pass `if (forceRefresh || !this.__totals)`  because its a race condition

**Comment by LarsDenBakker** [comment]
The services should store the request promise synchronously, and return that. This way it can guard against race conditions.
