### ISSUE TITLE
optimization for mobile

### ISSUE THREAD

**Issue by ThorbenJensen** [Code-for-All/lockdown#6]
the deployment at https://code-for-all.github.io/lockdown/ does not show well on my Samsung S10.
Might need some optimization for mobile?

**Comment by ThorbenJensen** [comment]
also, great project! :-)

**Comment by milovanderlinden** [comment]
Thanks! Can you post a screenshot? I would like to check what can be done about it.

**Comment by milovanderlinden** [comment]
I tested on my s10e, and indeed. Some work to do there.

**Comment by thepassle** [comment]
This should be solved now, we changed a lot in the frontend

**Comment by ThorbenJensen** [comment]
yes, looks much better now. :-)
