### ISSUE TITLE
link from country detail dialog to corresponding google sheets tab

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#61]
It would be really nice to have a link with something like "Improve this data" in the country detail dialog, and have it link through to the corresponding google sheets tab.

See:
![image](https://user-images.githubusercontent.com/17054057/77767841-f000f080-7041-11ea-999f-10279ab9cd0a.png)

The problem here is that google sheets assigns their own IDs to tabs, and there's seemingly no easy way to use a query parameter or something to go to a tab, e.g.: `https://docs.google.com/spreadsheet?tab=NL`. Maybe theres some google sheets scripting that can help with this?

As an alternative we could map the tabs `gid=1042330907` code per country to `worldmap.json`, but thats far from ideal 🙁

**Comment by ilyasfoo** [comment]
Maybe I can generate json for each country, like `/data/countries/nl` which contains any metadata we'd need to attach to any particular country

**Comment by ilyasfoo** [comment]
I've noticed in our [worldmap](https://github.com/Code-for-All/lockdown/blob/master/data/worldmap.json) there's multiple countries with duplicated ISO codes:`GIN, CYP, SOM`.



I think we'd need to establish a standardized unique reference from our worldmap geojson. I'd suggest we use a url safe slug generated from country name, such as 

```
United Arab Emirates => united-arab-emirates
Fr. S. Antarctic Lands => fr-s-antarctic-lands
```

**Comment by thepassle** [comment]
Eq Guinea should be GNQ, we should change this
Somaliland is not recognized by any nation, so should still be SOM?
googling around for country codes for N. Cyprus tells me its just CYP?

**Comment by ilyasfoo** [comment]
My original intention was to store "extra" country-related data (not shown immediately, only on user action) which my assumption could grow big, thus when combined into datafile.json was concerned about the total file size.

But if you think that's not going to be an issue for now then I'll just add that in datafile real quick.

**Comment by ilyasfoo** [comment]
Also on point of why needed that unique key: was because of the original idea needed to generate a reference like `/data/countries/malaysia` or `data/countries/nl`

**Comment by thepassle** [comment]
Thats a good point, actually.

As I see it, we need two JSON files:
- One to render the world map, in this file a country would only need an identifier (name/iso code?), and the state of lockdown
- Separate country files like `/data/countries/nl`, that will be individually requested when the dialog for a country is clicked, which contains all the other information

**Comment by ilyasfoo** [comment]
Yes, then i'll generate those data separately, will let you know when its done. Maybe just for now stick with ISO-2 like coronatracker does

**Comment by ilyasfoo** [comment]
Please check https://github.com/Code-for-All/lockdown/pull/64

**Comment by thepassle** [comment]
closing this, we have a solution for this now. See [here](https://github.com/Code-for-All/lockdown/pull/64#issuecomment-605530397)
