### ISSUE TITLE
Interface Data Entry

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/lockdown#7]
Since various people should be able to enter data, we decided to go for a gsuite sheet. On this sheet tabs will appear for various countries given in ISO3 code.

We need to build an interface, maybe even with an api to interface with the sheet and get the data available for the client.

**Comment by milovanderlinden** [comment]
Google has a sheet api with a great python interface. https://developers.google.com/sheets/api/quickstart/python

**Comment by LarsDenBakker** [comment]
I've worked with the google sheets API before, and it works pretty well. In the free plan you are limited in the amount of requests you can make, so I think it would be best to have some caching set up somewhere.
