### ISSUE TITLE
[backend + frontend] Type definitions

### ISSUE THREAD

**Issue by LarsDenBakker** [Code-for-All/lockdown#71]
Since both the frontend and backend are written in javascript, we can benefit from sharing the same type definitions.

I think it would be useful to write type definitions for the data sources, this can help a lot with auto completion and makes it easier to make changes.

We should switch to full typescript, but that's not necessarily required since we can enable type checking also with jsdocs in JS.

**Comment by ilyasfoo** [comment]
So far I've identified only two types of fields in the googlesheet. Let me know what you think of this:

```javascript
// shared/enums.js

const UNSPECIFIED_VALUE = 'unspecified';

const MEASURE = {
  NO: 'no',
  YES: 'yes',
  PARTIAL: 'partial',
  UNCLEAR: 'unclear',
  UNSPECIFIED: UNSPECIFIED_VALUE,
};

const TRAVEL = {
  PARTIAL: 'partial',
  UNCLEAR: 'unclear',
  NA: 'n/a',
  PROHIBITED: 'prohibited',
  ALLOWED: 'allowed',
  UNSPECIFIED: UNSPECIFIED_VALUE,
}

module.exports = {
  MEASURE: MEASURE,
  TRAVEL: TRAVEL,
  UNSPECIFIED_VALUE: UNSPECIFIED_VALUE,
}
```

**Comment by LarsDenBakker** [comment]
I think that's a good start! If something is unspecified, it should just not be there (undefined). If it's not an optional property, we should throw an error. Otherwise we can get a lot of unknown behavior in the front-end.

We will also need to describe the entire structure of the JSON files.

**Comment by ilyasfoo** [comment]
Alright I'll omit unspecified value, for now if value is not defined enum, it'll become undefined instead.

I think for optional property and structure description can be built later on @LarsDenBakker ?
Will need these enums quick to reduce technical debts ASAP, since frontend will start consuming data to build logic

**Comment by LarsDenBakker** [comment]
Yes I agree
