### ISSUE TITLE
[frontend + backend?] totals - countries in lockdown

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#74]
Requires https://github.com/Code-for-All/lockdown/issues/72 to be done

- [ ] We need to somehow get the amount of countries in lockdown and update the status in the top bar of the app.
  - (how do we get this? Do we loop through the countries and count how many countries are in lockdown on the frontend? Do we have another script for this that outputs a `totals.json` and fetch it with another service on the frontend?

- [ ] A strategy for these requests will need to be added to the service worker (network first)

**Comment by JFQueralt** [comment]
I am thinking about that and other consequences in terms of performance impact.
Thinking about doing totals, yes, maybe on an array per day. Gotta consider.

**Comment by ilyasfoo** [comment]
I think the script can total that up. The only drawback is our data is only as latest as script run, but that's a minor issue right?

**Comment by ilyasfoo** [comment]
Does "Partial" should be counted in total as well? @JFQueralt

**Comment by JFQueralt** [comment]
I am thinking about that and other consequences in terms of performance impact.
Thinking about doing totals, yes, maybe on an array per day. Gotta consider.

> 
> 
> Requires #72 to be done
> 
> We need to somehow get the amount of countries in lockdown and update the status in the top bar of the app (how do we get this? Do we loop through the countries and count how many countries are in lockdown on the frontend? Do we have another script for this that outputs a `totals.json` and fetch it with another service on the frontend?

I can generate the snapshots of those stats in the same way as the rest of the info. Good point.
Will work on it.

**Comment by JFQueralt** [comment]
> 
> 
> Does "Partial" should be counted in total as well? @JFQueralt

That's a good question. I guess yes since our position can be: Anything that is NOT free is simply NOT free kinda thing.
These elements are to be documented so that people understand where how are we measuring things.
