### ISSUE TITLE
[frontend - backend?] totals - people affected

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#75]
Requires https://github.com/Code-for-All/lockdown/issues/72 to be done

- [ ] We need to somehow get the amount of people affected by lockdowns and update the status in the top bar of the app. 
  - (how do we get this data? Do we have another script for this that outputs a `totals.json` and fetch it with another service on the frontend?)
- [ ] A strategy for these requests will need to be added to the service worker (network first)

**Comment by ilyasfoo** [comment]
So far we only have the territory-wide population for 2018, which I think might not represent this correctly. Any ideas @JFQueralt ?

**Comment by thepassle** [comment]
We should now be able to get this number with the data that we have right? (population.json, and all the countries with lockdown_status "yes|partially", im assuming)

**Comment by ilyasfoo** [comment]
Yes I think that's the best we got. I'll ping Jean to see if this logic is okay
