### ISSUE TITLE
[frontend - ux] legend

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#76]
We need a legend for the map, this needs a design and then be implemented in the frontend, it was discussed that this would be another item in the 'info' menu here:

![image](https://user-images.githubusercontent.com/17054057/77855582-90494780-71f1-11ea-8d5d-5d5280c6dd67.png)

- [x] needs design
- [ ] imlpement in frontend

**Comment by greenblue456** [comment]
would it not be better to have the legend somewhere on map itself?

**Comment by JFQueralt** [comment]
@greenblue456 We can look into that for v2, indeed (it's what makes sense).
Right now we don't want to touch the UI more than necessary so we rather add the legend on the Info panel.

Will work some sketch.

**Comment by JFQueralt** [comment]
@greenblue456 
Yes, that would be ideal.
To speed up v1 release, we decided to not make any more major changes to the interface.
We can work that out on for v2, for instance. Feel free to create a Card on the UI/UX board for that:
Suggestions List.

@thepassle 
Gonna make a quick drawing sample and send.

**Comment by JFQueralt** [comment]
![photo_2020-03-30_10-06-37](https://user-images.githubusercontent.com/9198668/77868548-3175e380-726e-11ea-902f-fc4de32a034d.jpg)

Bodycopy should logically go on the top.

The FORBIDDEN sign is on (?) because it could be too much visually. Anyway, just an idea.
@petrajaaskelainen, you think you can work some wireframe sample?

**Comment by thepassle** [comment]
<img width="529" alt="Screenshot 2020-03-30 at 09 04 25" src="https://user-images.githubusercontent.com/17054057/77884528-87925900-7265-11ea-868a-3e7925133f4d.png">

**Comment by aloptrbl** [comment]
hey, can I do this?

**Comment by thepassle** [comment]
Sure, please make a MR when you're done and I'll review it :)

**Comment by thepassle** [comment]
done in https://github.com/Code-for-All/lockdown/pull/148
