### ISSUE TITLE
[frontend - ux] offline state in country detail dialog

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#77]
would be nice to have a nice design for the offline state, currently we only show "Looks like you're offline :(", we can make this a nicer user friendly message with a nice design maybe?

This state will occur if a user has installed the app on their phone, clicks on a country while not connected to the internet

- [x] Needs a design
- [x] Need offline-icon from petra
- [x] Needs to be implemented in frontend

**Comment by JFQueralt** [comment]
![image](https://user-images.githubusercontent.com/9198668/77868700-b9f48400-726e-11ea-885c-7132841d3ec6.png)

![image](https://user-images.githubusercontent.com/9198668/77868718-c4168280-726e-11ea-8498-a43a7873db1a.png)
Source article: https://www.skcript.com/svr/offline-is-the-new-online/

**Comment by thepassle** [comment]
<img width="517" alt="Screenshot 2020-03-30 at 09 04 30" src="https://user-images.githubusercontent.com/17054057/77884544-8eb96700-7265-11ea-96a0-41d379a02723.png">
