### ISSUE TITLE
[frontend - backend] updates (menu item/dialog)

### ISSUE THREAD

**Issue by thepassle** [Code-for-All/lockdown#79]
We need a way/strategy to extract updates from the google sheets for this dialog:

![image](https://user-images.githubusercontent.com/17054057/77855776-f4b8d680-71f2-11ea-9b03-666bb616eaf0.png)

More info/designs [here](https://docs.google.com/spreadsheets/d/1_FFCVmQLxWVIqdgiuYT1ZgX1035A62vtvKt4Sh967IQ/edit#gid=410098306)

- [ ] We need a way to extract them from google sheets, new script probably
- [ ] Service on the frontend to fetch them
- [ ] visualize them in the dialog
- [ ] service worker strategy (network first)

In the original designs we showed 'notifications' (e.g.: small subtle blue dot on the icon, similar to the pwa update available pattern, see screenshot down below) when a new update was available, do we want/need that for v1? Or iterate on it, and for now only get e.g. the last 10 updates from the excel sheet? If we do want 'notifications', how can we achieve it? Or is this for v2?

![image](https://user-images.githubusercontent.com/17054057/77855831-511bf600-71f3-11ea-8d44-2337e4cfab46.png)

**Comment by ilyasfoo** [comment]
@JFQueralt couple of things:
- Update [sheet](https://docs.google.com/spreadsheets/d/1mVyQxxLxAF3E1dw870WHXTOLgYzmumojvzIekpgvLV0/edit#gid=907759727) needs to have timestamp to display like design
- We would only show latest 10 updates for V1 (script will do the sorting based on timestamp).

**Comment by JFQueralt** [comment]
Proposal:

Alpha (v1)
We do as mentioned, we extract only the latest 10 updates

Beta
I've been thinking about a suitable way to "customize" the Updates based on certain circumstances (for instance, you don't want ALL Updates to be New Entry type and that's bound to happen when we start entering all the life inputs).

Noted on the Timestamp, you are totally right. Adding up now.

**Comment by ilyasfoo** [comment]
Thanks @JFQueralt!

**Comment by JFQueralt** [comment]
I am actually thinking if it wouldn't be easier to do this with a bloody G Form.
Let me have a quick look at it.

**Comment by JFQueralt** [comment]
Alright
I created a form:
https://docs.google.com/forms/d/e/1FAIpQLScYQWrZ1nQv71u3pNuB-0fcPAdwAfkkhdBTGg__wyhyXux_BQ/viewform

(I'll work on polishing it later - I have 2 calls back to back in few minutes )

It is linked to our Data Source and I renamed the sheet to Updates. Same fields as before (same names too) PLUS the automatic Timestamp created by the form submission.

The sheet behaves nicely and I've been able to put some extra features and protections:
- Sheet can't be deleted by other Editors (only me)
- Relevant fields (Status, Type) have Data Validation and Conditional Format applied. Helps a lot and I am amazed this is possible coming from data linked to a G Form.

@ilyasfoo I think you can proceed with testing the extraction. Let me know if anything doesn't go well.

Note: I renamed the old Updates to Updates_Old for the time being. We can delete later.

**Comment by JFQueralt** [comment]
@ilyasfoo 
One thing: We have a different behavior here for Flagged.

In Data Entries Flagged status DOES NOT remove the data from the map. Otherwise you'd have a possible trolling entry point: people could flag data, we remove it and if done enough times you end up having no live data at all anymore.

In Updates, Flagged MUST not fetch the Update anymore until reviewed. The damage is less important and it matters that we remove it until it's solved.

**Comment by ilyasfoo** [comment]
Alright noted

**Comment by thepassle** [comment]
@JFQueralt are all the preparations for this in google sheets/the flow on how to enter this information for editors ready?

@ilyasfoo Do you think this will be much work to implement in the backend?

![image](https://user-images.githubusercontent.com/17054057/78701353-2aeb0a00-7907-11ea-8328-322f50422c52.png)

I think the data structure for this would be something like:

`updates.json`:
```js
{
  updates: [
    {
      type: "new|rectification|petition|announcement|promotion",
      title: "String",
      content: "String",
      link: "String",
      date: "String" // date as string?
    },
    // ... etc
  ]
}
```

**Comment by ilyasfoo** [comment]
@thepassle Not much, check out https://github.com/Code-for-All/lockdown/pull/142
