### ISSUE TITLE
Stats returning error

### ISSUE THREAD

**Issue by anyitomizayi** [Code-for-All/lockdown#84]
Stats returning error...currently for Myanmar and Yemen, so far

**Comment by thepassle** [comment]
Can confirm both 
![image](https://user-images.githubusercontent.com/17054057/77886221-c4138400-7268-11ea-8794-9687078cb9c7.png)


Its a problem with the coronatracker API, I've contacted them about

https://coronatracker.slack.com/archives/CSR0P04V8/p1585553218086800

**Comment by thepassle** [comment]
If the corona tracker api doesnt have data for a country, or has no cases, it'll return `[null]`. We guard against this now and show `0` instead. Fixed in: f5cca3657f195cdcf4eca111c331b48219fbe14b
