### ISSUE TITLE
Maldives not mapped/clickable

### ISSUE THREAD

**Issue by anyitomizayi** [Code-for-All/lockdown#85]

**Comment by milovanderlinden** [comment]
Solved by #155

**Comment by ilyasfoo** [comment]
Hey @milovanderlinden sorry this wasn't documented, the script uses base json at `backend/src/loaders/worldmap/base.json` to generate `worldmap.json`. I've copied your changes to the base json here https://github.com/Code-for-All/lockdown/pull/156
